# Generated by Django 3.1.2 on 2021-01-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_enable', models.CharField(choices=[('1', 'ENABLE'), ('0', 'DISABLE')], default='1', max_length=1)),
                ('mobile_ads_network', models.CharField(choices=[('admob', 'ADMOB'), ('fan', 'FACEBOOK_AUDIANCE NETWORK'), ('startapp', 'STARTAPP')], default='admob', max_length=8)),
                ('admob_app_id', models.CharField(blank=True, max_length=200, null=True)),
                ('admob_banner_ads_id', models.CharField(blank=True, max_length=200, null=True)),
                ('admob_interstitial_ads_id', models.CharField(blank=True, max_length=200, null=True)),
                ('fan_native_ads_placement_id', models.CharField(blank=True, max_length=200, null=True)),
                ('fan_banner_ads_placement_id', models.CharField(blank=True, max_length=200, null=True)),
                ('fan_interstitial_ads_placement_id', models.CharField(blank=True, max_length=200, null=True)),
                ('startapp_app_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(choices=[('vertical', 'VERTICAL'), ('grid', 'GRID')], default='vertical', max_length=8)),
                ('program_guide_enable', models.BooleanField(default=False)),
                ('mandatory_login', models.BooleanField(default=False)),
                ('genre_visible', models.BooleanField(default=True)),
                ('country_visible', models.BooleanField(default=False)),
            ],
        ),
    ]
