# Generated by Django 3.1.2 on 2021-01-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAPI', '0002_apkversioninfo_paymentconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adsconfig',
            options={'verbose_name_plural': 'Advertisement Configuration'},
        ),
        migrations.AlterModelOptions(
            name='apkversioninfo',
            options={'verbose_name_plural': 'APK Version Information'},
        ),
        migrations.AlterModelOptions(
            name='appconfig',
            options={'verbose_name_plural': 'APP Configuration'},
        ),
        migrations.AlterModelOptions(
            name='paymentconfig',
            options={'verbose_name_plural': 'Payment configuration'},
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='razorpay_key_secret',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
