# Generated by Django 3.1.2 on 2021-01-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAPI', '0003_auto_20210102_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apkversioninfo',
            name='version_name',
            field=models.CharField(default='v1.0.0', max_length=6),
        ),
    ]
