# Generated by Django 3.1.2 on 2021-01-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAPI', '0004_auto_20210102_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apkversioninfo',
            name='version_code',
            field=models.CharField(default='30', max_length=3),
        ),
    ]
