# Generated by Django 3.1.2 on 2021-01-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magnet',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='magnet',
            name='magnet',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='torrentkeyword',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
