# Generated by Django 3.1.2 on 2020-12-10 18:40

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imdbID', models.IntegerField(blank=True, null=True)),
                ('poster', models.ImageField(default='poster/poster.jpg', upload_to='poster')),
                ('banner', models.ImageField(default='banner/banner.jpg', upload_to='banner')),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('action', 'ACTION'), ('drama', 'DRAMA'), ('comedy', 'COMEDY'), ('romance', 'ROMANCE'), ('adventure', 'ADVENTURE'), ('animation', 'ANIMATION'), ('crime', 'CRIME'), ('documentary', 'DOCUMENTARY'), ('family', 'FAMILY'), ('fantasy', 'FANTASY'), ('horror', 'HORROR'), ('music', 'MUSIC'), ('science friction', 'SCI-FI'), ('thriller', 'THRILLER'), ('war', 'WAR')], max_length=40, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('trailer', models.URLField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('embed', models.URLField(blank=True, null=True)),
                ('download', models.URLField(blank=True, null=True)),
                ('views', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=283)),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
