# Generated by Django 3.1.2 on 2020-12-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201210_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
