# Generated by Django 3.1.2 on 2021-01-02 05:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201219_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', multiselectfield.db.fields.MultiSelectField(choices=[('list', 'LIST'), ('detail', 'DETAIL'), ('base', 'BASE')], max_length=14)),
                ('code', models.TextField()),
            ],
            options={
                'verbose_name': 'AdsPlacement',
            },
        ),
        migrations.AlterField(
            model_name='download',
            name='quality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='embed',
            name='quality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='magnet',
            name='quality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='quality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='webtor',
            name='quality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
