# Generated by Django 3.1.2 on 2020-12-10 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20201210_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
    ]
