# Generated by Django 3.1.2 on 2020-12-10 19:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('english', 'ENGLISH'), ('hindi', 'HINDI'), ('chinese', 'CHINESE'), ('punjabi', 'PUNJABI')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('recent', 'RECENTLY ADDED'), ('featured', 'FEATURED'), ('mostwatched', 'MOST WATCHED')], max_length=30, null=True),
        ),
    ]
