# Generated by Django 3.1.2 on 2020-12-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20201210_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('image', models.ImageField(default='casts/casts.jpg', upload_to='casts')),
                ('actress', models.BooleanField(default=True)),
                ('movie', models.ManyToManyField(to='movies.Movie')),
            ],
        ),
    ]
