# Generated by Django 3.1.2 on 2020-12-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_casts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Casts',
            new_name='Cast',
        ),
    ]
