# Generated by Django 3.1.2 on 2020-12-10 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20201210_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebTor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(blank=True, max_length=30, null=True)),
                ('source', models.CharField(max_length=2083)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_webtor', to='movies.movie')),
            ],
        ),
    ]
