# Generated by Django 3.1.2 on 2020-12-10 20:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20201210_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webtor',
            options={'verbose_name': 'Webtor'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('featured', 'FEATURED'), ('mostwatched', 'MOST WATCHED')], max_length=30, null=True),
        ),
    ]
