# Generated by Django 3.1.2 on 2020-12-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20201210_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tagline',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
