# Generated by Django 3.1.2 on 2020-12-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20201211_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Movie',
            new_name='movie',
        ),
    ]
