# Generated by Django 3.1.2 on 2020-12-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_auto_20201211_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='bannerURL',
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='posterURL',
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
    ]
