# Generated by Django 3.1.2 on 2020-12-12 06:43

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_auto_20201211_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion', multiselectfield.db.fields.MultiSelectField(choices=[('footer', 'FOOTER'), ('header', 'HEADER'), ('body', 'BODY')], max_length=30)),
                ('tag', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'StaticTag',
            },
        ),
        migrations.CreateModel(
            name='DynamicTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion', multiselectfield.db.fields.MultiSelectField(choices=[('footer', 'FOOTER'), ('header', 'HEADER'), ('body', 'BODY')], max_length=30)),
                ('tag', models.CharField(max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies_tag', to='movies.movie')),
            ],
            options={
                'verbose_name': 'DynamcTag',
            },
        ),
    ]
