# Generated by Django 3.1.2 on 2020-12-12 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_dynamictag_statictag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictag',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_tag', to='movies.movie'),
        ),
    ]
