# Generated by Django 3.1.2 on 2020-12-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_auto_20201212_0700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-commented_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='commented_on',
        ),
    ]
