# Generated by Django 3.1.2 on 2020-12-12 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_auto_20201212_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
