# Generated by Django 3.1.2 on 2020-12-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_terms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Terms',
            new_name='Term',
        ),
    ]
