# Generated by Django 3.1.2 on 2020-12-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0028_auto_20201213_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='actress',
        ),
        migrations.AddField(
            model_name='cast',
            name='imageURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
