# Generated by Django 3.1.2 on 2020-12-13 19:27

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0030_auto_20201213_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('en', 'ENGLISH'), ('hi', 'HINDI'), ('zh', 'CHINESE'), ('pa', 'PUNJABI'), ('ja', 'JAPANESE'), ('es', 'SPANISH'), ('fr', 'FRENCH'), ('ta', 'TAMIL'), ('te', 'TELUGU'), ('th', 'THAI'), ('tr', 'TURKISH'), ('vi', 'VIETNAMESE'), ('id', 'INDONESIAN'), ('ko', 'KOREAN'), ('fa', 'PERSIAN'), ('la', 'Latin')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production',
            field=models.DateField(blank=True, default='2020', null=True),
        ),
    ]
