# Generated by Django 3.1.2 on 2020-12-14 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0031_auto_20201213_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='production',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
