# Generated by Django 3.1.2 on 2020-12-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0032_auto_20201213_1930'),
        ('movies', '0032_auto_20201214_0943'),
    ]

    operations = [
    ]
